name: 'Git full diff'
description: 'Get the full diff of a git commit as usable output'
inputs:
  original-commit:
    description: 'The sha1 of the commit to diff against. Defaults to HEAD^'
    required: false
    default: 'HEAD^'
outputs:
  diff:
    description: "The full diff of the HEAD commit against original-commit"
    value: ${{ steps.get-git-diff.outputs.diff }}
runs:
  using: "composite"
  steps:
    - run: echo The provided SHA1 is "${{ inputs.original-commit }}".
      shell: bash
    - id: get-git-diff
      run: |
        EOF=$(dd if=/dev/urandom bs=15 count=1 status=none | base64)
        echo "diff<<$EOF" >> $GITHUB_OUTPUT
        echo "$(git diff ${{ inputs.original-commit }} --unified=0 | grep '^+' | grep -v '+++' | sed 's/^+//')" >> $GITHUB_OUTPUT
        echo "$EOF" >> $GITHUB_OUTPUT

      shell: bash