name: 'Git full diff'
description: 'Get the full diff of a git commit as usable output'
inputs:
  original-commit:  # id of input
    description: 'The sha1 of the commit to diff against. Defaults to HEAD^'
    required: false
    default: 'HEAD^'
outputs:
  diff:
    description: "The full diff of the HEAD commit against original-commit"
    value: ${{ steps.get-git-diff.outputs.diff }}
runs:
  using: "composite"
  steps:
    - run: echo The provided SHA1 is "${{ inputs.who-to-greet }}".
      shell: bash
    - id: get-git-diff
      run: |
        echo "diff=$(git diff ${{ inputs.original-commit }} --unified=0 | grep '^+' | grep -v '+++' | sed 's/^+//' | perl -pe '$_ = "" if 0 == $n++ && /^$/')"
        echo "random-number=$(echo $RANDOM)" >> $GITHUB_OUTPUT
      shell: bash